### ISSUE TITLE
PCB Dimensions

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFI2CADT01#1]
Díval jsem se teď na návrh PCB a překvapil mě tam rozměr. 23x25 mm. Není mi moc jasné, jak se k takovým rozměrům došlo. V posledním zápisu TFPCB je definováno takto: 

![image](https://user-images.githubusercontent.com/1194177/159895282-4ef6a035-a6df-4e3f-850b-cdedd6d91395.png)

Očekával bych tak šířku buď 24mm nebo 25mm ale 23mm je celkem překvapením.

**Comment by roman-dvorak** [comment]
K tomu se došlo tak, že pokud by na PCB měly být všechny konektory (co tam jsou) a mělo by to splňovat všechny tyto podmínky, tak by to byla hodně/zbytečně velká deska. Možná 30x20, 30x25.. 

Zároveň se neuvažovalo o krabičkování v standartní (neexistující) krabičce pro tento pattern. 

A tento modul má nepředpokládá montáž do míst, kam se montují senzory. 

Připadá mi to zde úplně korektní.
